# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  tags:
    include:
    - v*

stages:
- stage: Build
  jobs:
    - job: Build

      pool:
        vmImage: 'ubuntu-latest'

      steps:
      - task: UseNode@1
        inputs:
          version: '12.x'

      - task: Npm@1
        inputs:
          command: 'install'
        displayName: 'npm install'

      - script: |
          npm run build
        displayName: 'npm run build'

      - script: |
          npm pack
        displayName: 'Package for npm release'

      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: '*.tgz'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/npm'
        displayName: 'Copy npm package'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/npm'
          ArtifactName: 'npm'
          publishLocation: 'Container'
        displayName: 'Publish npm package as artifacts'

      # - task: CopyFiles@2
      #   inputs:
      #     SourceFolder: '$(Build.SourcesDirectory)/dist'
      #     Contents: '**'
      #     TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'
      #   displayName: 'Copy dist output'

      # - task: PublishBuildArtifacts@1
      #   inputs:
      #     PathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'
      #     ArtifactName: 'dist'
      #     publishLocation: 'Container'
      #   displayName: 'Publish dist files as artifacts'
        
- stage: Deploy
  jobs:
    - job: Deploy

      pool:
        vmImage: 'ubuntu-latest'

      steps:
      - script: |
          cd $(Build.SourcesDirectory)
          pName=$(ls *.tgz) 
          echo "##vso[task.setvariable variable=packageName]$pName"

      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'npm'
          downloadPath: '$(System.ArtifactsDirectory)'

      - task: npmAuthenticate@0
        inputs:
          workingFile: '$(Build.SourcesDirectory)/.npmrc'

      - script: |
          npm publish $(System.ArtifactsDirectory)/npm/$(packageName)